version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: safespot_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db        # MySQL 컨테이너 이름
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: safespot_db
    ports:
      - "4000:4000"       # 외부 4000 → 컨테이너 4000
    command: uvicorn main:app --host 0.0.0.0 --port 4000

volumes:
  db_data:
